### ISSUE TITLE
Issues with new typescript rules

### ISSUE THREAD

**Issue by SukkaW** [hexojs/eslint-config-hexo#37]
https://github.com/hexojs/eslint-config-hexo/blob/a1cfa6c8139d5b508d1bc6ac86d7c891e3310e74/ts.js#L13 introduced in #35

`env.mocha` shouldn't be added. cc @tomap @stevenjoezhang 

@yoshinorin please consider mark 4.2.0 as deprecated, and we need a bugfix version 4.2.1 published.

**Comment by yoshinorin** [comment]
> please consider mark 4.2.0 as deprecated, and we need a bugfix version 4.2.1 published.

v4.2.0 is not yet published.
Shall I wait to fix it?

**Comment by SukkaW** [comment]
> Shall I wait to fix it?

Yeah. I will open a PR to fix it.

**Comment by kecrily** [comment]
Why this rule is not needed in typescript version? Can you explain?

**Comment by SukkaW** [comment]
> Why this rule is not needed in typescript version? Can you explain?

@kecrily 

You already add this for `ts-test.js`:

https://github.com/hexojs/eslint-config-hexo/blob/418d964d0a4eb65ae986a760f5ffd37ef5d668a0/ts-test.js#L6-L8

Obviously, `mocha` does not exist in Node.js runtime, no need to add it in `ts.js` as well.

**Comment by yoshinorin** [comment]
I just published a new version.
Thank you :)

> https://www.npmjs.com/package/eslint-config-hexo/v/4.2.0
> https://github.com/hexojs/eslint-config-hexo/releases/tag/4.2.0
