### ISSUE TITLE
enable "Require confirmation of pull requests before merging"

### ISSUE THREAD

**Issue by segayuu** [hexojs/eslint-config-hexo#5]
I mistakenly committed directly to the master branch.
After that I did a Revert and did a rewind but I think that I should avoid making such mistakes in the future.
Should I enable "Require confirmation of pull requests before merging" setting in the master branch?

**Comment by NoahDragon** [comment]
Agree. BTW, is there a setting for this?

**Comment by segayuu** [comment]
see https://help.github.com/articles/about-protected-branches/

**Comment by tomap** [comment]
I just enabled protected branch on master, but that did not protect against a direct edit on master via the web interface. That seems strange or I did something wrong...?

**Comment by SukkaW** [comment]
> I just enabled protected branch on master, but that did not protect against a direct edit on master via the web interface. That seems strange or I did something wrong...?

You are one of the owners of the org, so you can still modify the master branch directly (just like merge a PR without review). That's intended.

**Comment by tomap** [comment]
Understood. I believe we can close this issue then!
