### ISSUE TITLE
DeprecationWarning: The `punycode` module is deprecated

### ISSUE THREAD

**Issue by lorezyra** [hexojs/eslint-config-hexo#53]
```zsh
(node:29131) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Can we update the module to replace "punycode"?

**Comment by uiolee** [comment]
`eslint-config-hexo` doesn't use `punycode`

![dependencies](https://github.com/hexojs/eslint-config-hexo/assets/22849383/13d15d2f-33a9-438d-8c5b-3d34230d7195)

**Comment by lorezyra** [comment]
Apologies... You are correct that it's not a direct dependency. 

![image](https://github.com/hexojs/eslint-config-hexo/assets/1673222/75dc4bc8-3cac-4ff4-99bb-09a976bad27b)

I've created an issue on [`uri-js`](https://github.com/garycourt/uri-js) project to update it. 🙇🏻‍♀️

## Opened ticket
- https://github.com/garycourt/uri-js/issues/96

**Comment by domdomegg** [comment]
There is a PR up in uri-js to fix this: https://github.com/garycourt/uri-js/pull/95
