### ISSUE TITLE
Possible errors & improvements.

### ISSUE THREAD

**Issue by ivan-nginx** [hexojs/eslint-config-hexo#8]
1. When i install config globally, `plugin:node/recommended` will install into `eslint-config-hexo` directory (under subdir). And plugin actually not work, because `eslint` must see `node` plugin in same level hierarchy. But then i install it locally, `node` plugin will placed in same level as `eslint`.

   ```bash
   node -v && npm -v
   v6.14.0
   3.10.10
   ```

   ```bash
   [root@localhost ivan-nginx]# npm i -g eslint-config-hexo
   /usr/lib
   ├── UNMET PEER DEPENDENCY eslint@>= 3.1.0
   └─┬ eslint-config-hexo@3.0.0
     ├── UNMET PEER DEPENDENCY eslint@>=3.1.0
     └─┬ eslint-plugin-node@5.2.1
       ├── ignore@3.3.8
       ├─┬ minimatch@3.0.4
       │ └─┬ brace-expansion@1.1.11
       │   ├── balanced-match@1.0.0
       │   └── concat-map@0.0.1
       ├─┬ resolve@1.7.1
       │ └── path-parse@1.0.5
       └── semver@5.3.0
   
   npm WARN eslint-config-hexo@3.0.0 requires a peer of eslint@>= 3.1.0 but none was installed.
   npm WARN eslint-plugin-node@5.2.1 requires a peer of eslint@>=3.1.0 but none was installed.
   ```

   Solution is — install `eslint-plugin-node` separately:
   ```bash
   npm i -g eslint-config-hexo eslint-plugin-node
   ```

2. ~~There are duplicate parameters in `eslint.js`: `dot-notation` and `no-multi-str`. And i also see other parameters which already by default in `eslint:recommended` settings.~~ Fixed in #6 
3. All `'error'` strings can be sucessfully replaced by `2`: https://eslint.org/docs/user-guide/configuring#configuring-rules
4. No need to define `parserOptions: { ecmaVersion: 6 }` parameter if `env: { es6: true }` already defined: https://eslint.org/docs/user-guide/configuring#specifying-parser-options
5. Deprecated parameter `'eqeqeq': ['error', 'allow-null']`: https://eslint.org/docs/rules/eqeqeq#allow-null
6. `strict` option not needed for ES6, because in ES6 this mode [turned on by default](https://eslint.org/docs/rules/strict#rule-details).

***

About pull #6:

1. `no-extra-label` now in [Best Practices](https://eslint.org/docs/rules/#best-practices) section.
2. `no-mixed-operators` now in [Stylistic Issues](https://eslint.org/docs/rules/#stylistic-issues) section.
3. `comma-dangle` can be just `error`, [`never` parameter is default for now](https://eslint.org/docs/rules/comma-dangle#options).
4. `comma-spacing` can be just `error`, [`before: false, after: true` is default for now](https://eslint.org/docs/rules/comma-spacing#options).
5. `comma-style` can be just `error`, [`last` is default for now](https://eslint.org/docs/rules/comma-style#options).
6. `computed-property-spacing` can be just `error`, [`never` is default for now](https://eslint.org/docs/rules/computed-property-spacing#options).
7. `key-spacing` can be just `error`, [`beforeColon: false, afterColon: true` is default for now](https://eslint.org/docs/rules/key-spacing#options).
    But i suggest to set [`{"align": "colon"}`](https://eslint.org/docs/rules/key-spacing#align) parameter.
8. `keyword-spacing` can be just `error`, no needed to set empty `['error', {}]` parameters.
9. `linebreak-style` can be just `error`, [`unix` is default for now](https://eslint.org/docs/rules/linebreak-style#options).
10. `lines-around-comment` can be just `error`, [`{ beforeBlockComment: true }` is default for now](https://eslint.org/docs/rules/lines-around-comment#options).
11. `semi` can be just `error`, [`always` is default for now](https://eslint.org/docs/rules/semi#options).
12. `semi-spacing` can be just `error`, [`before: false, after: true` is default for now](https://eslint.org/docs/rules/semi-spacing#options).
13. `space-before-blocks` can be just `error`, [`always` is default for now](https://eslint.org/docs/rules/space-before-blocks#options).
14. `space-before-function-paren` can be just `error`, [`always` is default for now](https://eslint.org/docs/rules/space-before-function-paren#options).
15. `space-in-parens` can be just `error`, [`never` is default for now](https://eslint.org/docs/rules/space-in-parens#options).
16. `spaced-comment` can be just `error`, [`always` is default for now](https://eslint.org/docs/rules/spaced-comment#options).
17. `template-tag-spacing` can be just `error`, [`never` is default for now](https://eslint.org/docs/rules/template-tag-spacing#options).
18. `unicode-bom` can be just `error`, [`never` is default for now](https://eslint.org/docs/rules/unicode-bom#options).
19. `rest-spread-spacing` can be just `error`, [`never` is default for now](https://eslint.org/docs/rules/rest-spread-spacing#options).
20. `template-curly-spacing` can be just `error`, [`never` is default for now](https://eslint.org/docs/rules/template-curly-spacing#options).
21. `yield-star-spacing` can be just `error`, [`after` is default for now](https://eslint.org/docs/rules/yield-star-spacing#after).
22. `yoda` can be just `error`, [`never` is default for now](https://eslint.org/docs/rules/yoda#never).

**Comment by tcrowe** [comment]
Thank you @theme-next. Those are good suggestions and it looks like @segayuu will incorporate this into his work.

**Comment by ivan-nginx** [comment]
NP, dudes. :ok_hand:

**Comment by segayuu** [comment]
thank @JLHwung!
